### ISSUE TITLE
use cases

### ISSUE THREAD

**Issue by brucou** [leontrolski/dnjs#1]
Hi there,

I was reviewing this and was asking myself what are the possible use cases for it? How do you personally plan to use it and what were the motivation for you to write it?

If we limit ourselves to HTML/CSS generation, there are a number of ways to do that -- ejs, mustache, nunjucks come to mind). Mustache does not go far in terms of custom logic, nunjucks goes farther with template inheritance, filters and more, ejs allows to use the full JavaScript language. dnjs looks nice for the simplicity (no templating language to learn, only hyperscript (or m)). I wonder if there is anything else that sets it apart.

Congratulations in any case for tackling this problem space!

**Comment by leontrolski** [comment]
Hi, a few days ago, I wrote up a post on how one might use `dnjs` - https://leontrolski.github.io/semi-isomorphic.html for templating (I'd agree, I think the configuration use case is less interesting). 

As far as the project goes, I still think there's a kernel of a good idea in it, but until someone (maybe me) writes a larger project with it, it's unclear whether the "correct" subset of js has been picked. Also, there are known issues with eg. error handling that leave it not prod-ready right now.
